In [1]:
# Soal 4
import pandas as pd

alphabet = pd.Series({
    "a": 1,
    "b": 2,
    "c": 3,
    "d": 4,
    "e": 5,
    "f": 6,
    "g": 7,
    "h": 8,
    "i": 9,
    "j": 10,
    "k": 11,
    "l": 12,
    "m": 13,
    "n": 14,
    "o": 15,
    "p": 16,
    "q": 17,
    "r": 18,
    "s": 19,
    "t": 20,
    "u": 21,
    "v": 22,
    "w": 23,
    "x": 24,
    "y": 25,
    "z": 26,
})

print(alphabet)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

In [7]:
# Soal 5
import numpy as np
import pandas as pd

series = pd.Series(np.random.randint(1,5,size=(100)))

print(series)
print("\n")

occurence = series.value_counts()

print("Jumlah angka:")
print(occurence)
print("\n")

print("Dua paling tinggi:")
print(occurence.nlargest(2))

0     1
1     3
2     2
3     3
4     1
     ..
95    2
96    1
97    1
98    2
99    3
Length: 100, dtype: int32


Jumlah angka:
2    30
3    28
1    23
4    19
dtype: int64


Dua paling tinggi:
2    30
3    28
dtype: int64

In [21]:
# Soal 6
import pandas as pd
import seaborn as sns

mpg = sns.load_dataset('mpg')

print(mpg.nlargest(5, ['mpg']))
print("\n")
print(mpg[['origin', 'name']].describe())
print("\n")
print(mpg.columns)
print("\n")
print(mpg.isna().sum())

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9
329  44.6          4          91.0        67.0    1850          13.8
325  44.3          4          90.0        48.0    2085          21.7
394  44.0          4          97.0        52.0    2130          24.6
326  43.4          4          90.0        48.0    2335          23.7

     model_year  origin                  name
322          80   japan             mazda glc
329          80   japan   honda civic 1500 gl
325          80  europe  vw rabbit c (diesel)
394          82  europe             vw pickup
326          80  europe    vw dasher (diesel)


       origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6


Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')


mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64